[package]
name = "javamanager"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
colored = "3.0.0"
dirs = "6.0.0"
either = "1.15.0"
libc = { version = "0.2.174", features = ["std"] }
rustix = { version = "1.0.7", features = ["std"] }
